/*
Copyright 2024 Generated by openapi-operator-gen.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
*/

package runtime

import (
	"fmt"
	"net/url"
	"reflect"
	"strings"
)

// IsZeroValue checks if a value is the zero value for its type.
// This is useful for determining whether to include optional fields in API requests.
func IsZeroValue(v interface{}) bool {
	if v == nil {
		return true
	}
	val := reflect.ValueOf(v)
	return val.IsZero()
}

// URLBuilder constructs URLs with path parameter substitution and query string building.
// It provides a fluent API for building REST API URLs with path parameters (e.g., /pet/{petId})
// and query parameters (e.g., ?status=available&tags=tag1&tags=tag2).
type URLBuilder struct {
	basePath    string
	pathParams  map[string]string
	queryParams url.Values
	resourceID  string
}

// NewURLBuilder creates a new URLBuilder with the given base path template.
// The basePath can contain path parameter placeholders in the form {paramName}.
//
// Example:
//
//	builder := NewURLBuilder("/pet/{petId}/uploadImage")
func NewURLBuilder(basePath string) *URLBuilder {
	return &URLBuilder{
		basePath:    basePath,
		pathParams:  make(map[string]string),
		queryParams: make(url.Values),
	}
}

// WithPathParam adds a path parameter to substitute in the URL template.
// Empty values are ignored.
//
// Example:
//
//	builder.WithPathParam("petId", "123") // replaces {petId} with 123
func (b *URLBuilder) WithPathParam(name, value string) *URLBuilder {
	if value != "" {
		b.pathParams[name] = value
	}
	return b
}

// WithPathParamInt adds an integer path parameter to substitute in the URL template.
// Zero values are ignored.
//
// Example:
//
//	builder.WithPathParamInt("petId", 123) // replaces {petId} with 123
func (b *URLBuilder) WithPathParamInt(name string, value int64) *URLBuilder {
	if value != 0 {
		b.pathParams[name] = fmt.Sprintf("%d", value)
	}
	return b
}

// WithPathParams adds multiple path parameters at once.
// Empty values are ignored.
func (b *URLBuilder) WithPathParams(params map[string]string) *URLBuilder {
	for name, value := range params {
		b.WithPathParam(name, value)
	}
	return b
}

// WithQueryParam adds a single query parameter.
// Empty values are ignored.
//
// Example:
//
//	builder.WithQueryParam("status", "available") // adds ?status=available
func (b *URLBuilder) WithQueryParam(name, value string) *URLBuilder {
	if value != "" {
		b.queryParams.Add(name, value)
	}
	return b
}

// WithQueryParamInt adds an integer query parameter.
// Zero values are ignored.
//
// Example:
//
//	builder.WithQueryParamInt("limit", 10) // adds ?limit=10
func (b *URLBuilder) WithQueryParamInt(name string, value int64) *URLBuilder {
	if value != 0 {
		b.queryParams.Add(name, fmt.Sprintf("%d", value))
	}
	return b
}

// WithQueryParamFloat adds a float query parameter.
// Zero values are ignored.
//
// Example:
//
//	builder.WithQueryParamFloat("price", 19.99) // adds ?price=19.99
func (b *URLBuilder) WithQueryParamFloat(name string, value float64) *URLBuilder {
	if value != 0 {
		b.queryParams.Add(name, fmt.Sprintf("%g", value))
	}
	return b
}

// WithQueryParamBool adds a boolean query parameter.
// Only adds the parameter if value is true.
//
// Example:
//
//	builder.WithQueryParamBool("verbose", true) // adds ?verbose=true
func (b *URLBuilder) WithQueryParamBool(name string, value bool) *URLBuilder {
	if value {
		b.queryParams.Add(name, "true")
	}
	return b
}

// WithQueryParamArray adds multiple values for the same query parameter.
// Empty slices and empty values within the slice are ignored.
//
// Example:
//
//	builder.WithQueryParamArray("tags", []string{"tag1", "tag2"}) // adds ?tags=tag1&tags=tag2
func (b *URLBuilder) WithQueryParamArray(name string, values []string) *URLBuilder {
	for _, v := range values {
		if v != "" {
			b.queryParams.Add(name, v)
		}
	}
	return b
}

// WithQueryParamIntArray adds multiple integer values for the same query parameter.
//
// Example:
//
//	builder.WithQueryParamIntArray("ids", []int64{1, 2, 3}) // adds ?ids=1&ids=2&ids=3
func (b *URLBuilder) WithQueryParamIntArray(name string, values []int64) *URLBuilder {
	for _, v := range values {
		b.queryParams.Add(name, fmt.Sprintf("%d", v))
	}
	return b
}

// WithQueryParams adds multiple query parameters from a map.
// Empty values are ignored.
func (b *URLBuilder) WithQueryParams(params map[string]string) *URLBuilder {
	for name, value := range params {
		b.WithQueryParam(name, value)
	}
	return b
}

// WithResourceID sets a resource ID to append to the path if not already present via path params.
// Used for GET/PUT/DELETE operations on specific resources.
//
// Example:
//
//	builder.WithResourceID("123") // appends /123 to path if not already present
func (b *URLBuilder) WithResourceID(resourceID string) *URLBuilder {
	b.resourceID = resourceID
	return b
}

// Build constructs the final URL string.
// It substitutes path parameters, optionally appends the resource ID, and adds query parameters.
//
// Example:
//
//	url := NewURLBuilder("/pet/{petId}").
//	    WithPathParam("petId", "123").
//	    WithQueryParam("fields", "name,status").
//	    Build("https://api.example.com")
//	// Returns: https://api.example.com/pet/123?fields=name%2Cstatus
func (b *URLBuilder) Build(baseURL string) string {
	path := b.substitutePath()

	// Append resource ID if set and not already in path
	if b.resourceID != "" && !b.isResourceIDInPath() {
		if !strings.HasSuffix(path, "/") {
			path = path + "/"
		}
		path = path + url.PathEscape(b.resourceID)
	}

	// Combine base URL and path
	result := strings.TrimSuffix(baseURL, "/") + path

	// Append query string if present
	if len(b.queryParams) > 0 {
		result = result + "?" + b.queryParams.Encode()
	}

	return result
}

// BuildForCreate constructs URL for POST operations (no resource ID appended).
// Only substitutes path parameters and adds query parameters.
//
// Example:
//
//	url := NewURLBuilder("/pet").
//	    WithQueryParam("api_key", "secret").
//	    BuildForCreate("https://api.example.com")
//	// Returns: https://api.example.com/pet?api_key=secret
func (b *URLBuilder) BuildForCreate(baseURL string) string {
	path := b.substitutePath()

	// Combine base URL and path (no resource ID for create)
	result := strings.TrimSuffix(baseURL, "/") + path

	// Append query string if present
	if len(b.queryParams) > 0 {
		result = result + "?" + b.queryParams.Encode()
	}

	return result
}

// substitutePath replaces path parameter placeholders with their values
func (b *URLBuilder) substitutePath() string {
	path := b.basePath

	for name, value := range b.pathParams {
		placeholder := "{" + name + "}"
		// URL-encode the value for safe path usage
		path = strings.Replace(path, placeholder, url.PathEscape(value), 1)
	}

	return path
}

// isResourceIDInPath checks if the resource ID is already present in the path via a path param
func (b *URLBuilder) isResourceIDInPath() bool {
	if b.resourceID == "" {
		return false
	}

	for _, v := range b.pathParams {
		if v == b.resourceID {
			return true
		}
	}

	return false
}

// HasUnsubstitutedParams checks if any path parameter placeholders remain unsubstituted.
// This can be used to detect configuration errors.
//
// Example:
//
//	builder := NewURLBuilder("/pet/{petId}") // forgot to set petId
//	if builder.HasUnsubstitutedParams() {
//	    // handle error
//	}
func (b *URLBuilder) HasUnsubstitutedParams() bool {
	path := b.substitutePath()
	return strings.Contains(path, "{") && strings.Contains(path, "}")
}

// GetUnsubstitutedParams returns a list of path parameter names that haven't been substituted.
//
// Example:
//
//	builder := NewURLBuilder("/pet/{petId}/photo/{photoId}").
//	    WithPathParam("petId", "123")
//	params := builder.GetUnsubstitutedParams() // returns ["photoId"]
func (b *URLBuilder) GetUnsubstitutedParams() []string {
	path := b.substitutePath()
	var params []string

	for {
		start := strings.Index(path, "{")
		if start == -1 {
			break
		}
		end := strings.Index(path[start:], "}")
		if end == -1 {
			break
		}
		params = append(params, path[start+1:start+end])
		path = path[start+end+1:]
	}

	return params
}

// Reset clears all path parameters, query parameters, and resource ID.
// The base path is preserved.
func (b *URLBuilder) Reset() *URLBuilder {
	b.pathParams = make(map[string]string)
	b.queryParams = make(url.Values)
	b.resourceID = ""
	return b
}

// Clone creates a copy of the URLBuilder with the same configuration.
// Useful for building multiple similar URLs.
func (b *URLBuilder) Clone() *URLBuilder {
	clone := &URLBuilder{
		basePath:    b.basePath,
		pathParams:  make(map[string]string),
		queryParams: make(url.Values),
		resourceID:  b.resourceID,
	}

	for k, v := range b.pathParams {
		clone.pathParams[k] = v
	}

	for k, v := range b.queryParams {
		clone.queryParams[k] = append([]string{}, v...)
	}

	return clone
}
